# Generated by Django 5.0.7 on 2024-08-29 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicyear',
            name='year',
            field=models.IntegerField(choices=[(2024, 2024), (2025, 2025), (2026, 2026)]),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(choices=[('BIO & CHEM', 'BIO & CHEM'), ('PHYS & CHEM', 'PHY & CHEM'), ('MATH & PHY', 'MATH & PHY'), ('MATH & CHEM', 'MATH & CHEM'), ('HIS & CRE', 'HIS & CRE'), ('GEO & HIS', 'GEO & HIS'), ('HIS & KIS', 'HIS & KIS'), ('KIS & CRE', 'KIS & CRE'), ('ENG/LIT', 'ENG/LIT'), ('MATH/COMP', 'MATH/COMP'), ('MATH/BUS', 'MATH/BUS'), ('HSC/BIO', 'HSC/BIO'), ('MATH/GEO', 'MATH/GEO'), ('HIS/P.E', 'HIS/P.E')], max_length=100),
        ),
    ]
