# Generated by Django 4.0.6 on 2024-09-05 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_event_title_alter_news_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('G', 'G'), ('B', 'B'), ('H', 'H'), ('S', 'S'), ('F', 'F'), ('A', 'A'), ('A1', 'A1'), ('A2', 'A2')], max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='grade',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_number', models.CharField(max_length=5, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='main.stream')),
            ],
        ),
        migrations.AddField(
            model_name='stream',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='main.grade'),
        ),
    ]
