# Generated by Django 5.0.7 on 2024-09-06 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_stream_alter_grade_name_student_stream_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='kcpe',
            field=models.IntegerField(default=500, max_length=3),
            preserve_default=False,
        ),
    ]
