# Generated by Django 5.0.7 on 2024-09-06 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_student_kcpe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='kcpe',
            field=models.IntegerField(),
        ),
    ]
